### ISSUE TITLE
How to sync with Aftership?

### ISSUE THREAD

**Issue by TenGauge** [mrmonsters/magento2-aftership#1]
API created in Aftership and added + enabled in Config panel of M2.  Will this send out currently in transit shipments, or only new order shipments from this point forward?  Is there a way to force current shipments from Magento to Aftership?  Thank you for making this module, I have been missing this greatly since upgrading from M1.

**Comment by mrmonsters** [comment]
Glad to help. 👍 

By default, there is a [cron job](https://github.com/mrmonsters/magento2-aftership/blob/b9efe7463a8f8d3db0bd0e05e8e33d440c750c9c/Cron/UploadTracking.php#L74) which upload shipments from the **past 3 hours upon initial installation**. During the next iteration, it will continue from where it left off. 

This configuration remains the **same** with the one in Magento 1 module.

**Comment by TenGauge** [comment]
Great thanks!  It doesn't seem to be working on my end but let me try and make sure that the Cron job did infact install.

**Comment by TenGauge** [comment]
I'm not getting anything pushing out to Aftership. I've got my API address created @ Aftership, plugged in to my config on M2 with Enable and Cron set to yes.  I'm running the latest version of M2.

**Comment by mrmonsters** [comment]
Hi @TenGauge. First of all, sorry that I was not able to work on this issue earlier due to ongoing tasks.

#Anyway, I have added a fix in #2. This is already made available in release 1.0.4. Please try it out if you are still using it. Thanks!
